# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='\u671f\u6b21')),
            ],
            options={
                'verbose_name': '\u671f\u6b21\u4fe1\u606f',
                'verbose_name_plural': '\u671f\u6b21\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='StudyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyTeam', models.CharField(max_length=30, verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u5b66\u4e60\u5c0f\u7ec4',
                'verbose_name_plural': '\u5b66\u4e60\u5c0f\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d\uff08\u62fc\u97f3\uff09')),
                ('nameZh', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('examinationCode', models.CharField(max_length=6, verbose_name='\u5ba1\u67e5\u4ee3\u7801')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examiner_auth.Grade')),
                ('studyTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examiner_auth.StudyTeam')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u67e5\u5458\u914d\u7f6e')),
            ],
            options={
                'verbose_name': '\u5ba1\u67e5\u5458\u914d\u7f6e',
                'verbose_name_plural': '\u5ba1\u67e5\u5458\u914d\u7f6e',
            },
        ),
    ]
