# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlyTask', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='\u4efb\u52a1\u91cf')),
                ('year', models.PositiveIntegerField(choices=[(2012, '2012\u5e74'), (2013, '2013\u5e74'), (2014, '2014\u5e74'), (2015, '2015\u5e74'), (2016, '2016\u5e74'), (2017, '2017\u5e74'), (2018, '2018\u5e74')], verbose_name='\u5e74\u4efd')),
                ('month', models.PositiveIntegerField(choices=[(1, '\u4e00\u6708'), (2, '\u4e8c\u6708'), (3, '\u4e09\u6708'), (4, '\u56db\u6708'), (5, '\u4e94\u6708'), (6, '\u516d\u6708'), (7, '\u4e03\u6708'), (8, '\u516b\u6708'), (9, '\u4e5d\u6708'), (10, '\u5341\u6708'), (11, '\u5341\u4e00\u6708'), (12, '\u5341\u4e8c\u6708')], verbose_name='\u6708\u4efd')),
                ('theExaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6309\u6708\u4efb\u52a1\u91cf',
                'verbose_name_plural': '\u6309\u6708\u4efb\u52a1\u91cf',
            },
        ),
        migrations.CreateModel(
            name='task_submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yiChuAn', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\u5df2\u51fa\u6848')),
                ('xyJian', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='XY\u6848\u4ef6')),
                ('daiChuAn', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\u5f85\u51fa\u6848')),
                ('xinFenDaiShen', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\u65b0\u5206\u5f85\u5ba1')),
                ('chouZhongZhiJian', models.IntegerField(default=0, verbose_name='\u62bd\u4e2d\u8d28\u68c0\uff08\u6807\u51c6\u4ef6\uff09')),
                ('yiTongBeiZhu', models.CharField(default='\u65e0', max_length=200, verbose_name='\u4e00\u901a\u5907\u6ce8\uff08\u8c03\u5242\u60c5\u51b5\uff09')),
                ('shouQuan', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\u6388\u6743')),
                ('boHui', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\u9a73\u56de')),
                ('shiChe', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='\u89c6\u64a4')),
                ('jieAnBeiZhu', models.CharField(default='\u65e0', max_length=200, verbose_name='\u51fa\u6848\u5907\u6ce8\uff08\u8c03\u5242\u60c5\u51b5\uff09')),
                ('submitTime', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('theExaminer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u91cf\u63d0\u4ea4',
                'verbose_name_plural': '\u4efb\u52a1\u91cf\u63d0\u4ea4',
            },
        ),
    ]
