# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_task',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, '\u4e00\u6708'), (2, '\u4e8c\u6708'), (3, '\u4e09\u6708'), (4, '\u56db\u6708'), (5, '\u4e94\u6708'), (6, '\u516d\u6708'), (7, '\u4e03\u6708'), (8, '\u516b\u6708'), (9, '\u4e5d\u6708'), (10, '\u5341\u6708'), (11, '\u5341\u4e00\u6708'), (12, '\u5341\u4e8c\u6708')], verbose_name='\u6708\u4efd'),
        ),
        migrations.AlterField(
            model_name='monthly_task',
            name='year',
            field=models.PositiveIntegerField(choices=[(2012, '2012\u5e74'), (2013, '2013\u5e74'), (2014, '2014\u5e74'), (2015, '2015\u5e74'), (2016, '2016\u5e74'), (2017, '2017\u5e74'), (2018, '2018\u5e74')], verbose_name='\u5e74\u4efd'),
        ),
    ]
